version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - '6379:6379'


  django-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=django_drf_proj_kurs
      - POSTGRES_PASSWORD=mysecretpasswond
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  django-app:
    container_name: django_app
    build:
      dockerfile: Dockerfile
      context: .
    tty: true
    command: sh -c "sleep 3 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      django-db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    env_file:
      - .env
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - django-app

  celery_beat:
    build: .
    tty: true
    env_file:
      - .env
    restart: always
    command: celery -A config beat -l INFO -S django
    depends_on:
      - celery
      - redis
      - django-app

volumes:
  pg_data: