# Generated by Django 4.2.7 on 2023-11-22 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_name', models.CharField(max_length=100, verbose_name='Habit Name')),
                ('habit_description', models.TextField(blank=True, null=True, verbose_name='Habit Description')),
                ('habit_action', models.TextField(verbose_name='Habit Action')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Is Pleasant')),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=10, verbose_name='Period In Minutes')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Reward')),
                ('time_to_complete', models.PositiveIntegerField()),
                ('is_public', models.BooleanField(default=False, verbose_name='is Public')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Habit Creator')),
                ('pleasant_habit', models.ManyToManyField(blank=True, to='habit.habit', verbose_name='Pleasant Habit')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
